version: '3.1'

services: 
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment: 
            - MYSQL_DATABASE=wp-db
        volumes: 
            - dbdata:/var/lib/mysql
        command: '--default-authentication-plugin=mysql_native_password'
        networks: 
            - wp-network
    wp:
        depends_on: 
            - db
        image: wordpress:5.3.2-fpm
        container_name: wp
        restart: unless-stopped
        env_file: .env
        environment: 
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=wp-db
        volumes: 
            - wpdata:/var/www/html
            - ./wp-content:/var/www/html/wp-content/
        networks: 
            - wp-network
    
    webserver:
        depends_on: 
            - wp
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports: 
            - "8080:80"
        volumes: 
            - wpdata:/var/www/html
            - ./nginx-conf/:/etc/nginx/conf.d/
            - ./wp-content:/var/www/html/wp-content/
        networks: 
            - wp-network
volumes: 
    dbdata:
    wpdata:
        
networks: 
    wp-network:
        driver: bridge


    